### ISSUE TITLE
Screencasts

### ISSUE THREAD

**Issue by carlosrocha** [carlosrocha/vim-chrome-devtools#1]

**Comment by carlosrocha** [comment]
![vim-chrome-devtools_css](https://user-images.githubusercontent.com/312351/39974298-73a352ea-56ed-11e8-88a3-9e4846ac6cae.gif)

**Comment by carlosrocha** [comment]
## JavaScript Evaluation

![vim-chrome-devtools-eval](https://user-images.githubusercontent.com/312351/39975472-5c402892-56f4-11e8-906f-fed761dc66e9.gif)

**Comment by carlosrocha** [comment]
## CSS live reload
![vim-chrome-devtools-css](https://user-images.githubusercontent.com/312351/39975780-335638a2-56f6-11e8-945a-128fe59fa76c.gif)

**Comment by audrew** [comment]
Its not very clear of what it does? Does that mean I can use  devtools with vim? Surf between network , console, inspector tabs?
