### ISSUE TITLE
Not an editor command

### ISSUE THREAD

**Issue by jkassis** [carlosrocha/vim-chrome-devtools#3]
Having trouble installing... the remote plugin is registered, but vim doesn't recognize the commands.

**Comment by carlosrocha** [comment]
What command are you trying?

**Comment by alex-ameen** [comment]
I'm having the same issue (mentioned in the other issue as well).
None of the plugins commands, help pages, are being recognized by Neovim.
I can see that Vim-Plug is in fact installing the repo, and registering remotely with Node; but Neovim has none of the commands. `:ChromeDevToolsConnect` nada.

**Comment by alex-ameen** [comment]
I found the issue. You can't symlink in a Neovim remote plugin (as this repo attempts to). It's a security risk and Neovim explicitly prohibits it. The plugin is being ignored by Neovim intentionally for this reason. This also explains why some users were unable to remove the plugin through Vim-Plug, which was being trapped in an infinitely recursive source crawl.

**Comment by mirosval** [comment]
@carlosrocha I'm having the same problem. The connection to chrome seems to work, but I can't invoke the reload function.

**Comment by haskelcurry** [comment]
Same issue here, is there any workaround?

**Comment by psacawa** [comment]
Also facing this
