### ISSUE TITLE
When trying to uninstall after `nvim +PlugClean` neovim crashes and never finishes clean.

### ISSUE THREAD

**Issue by integrate-your-mind** [carlosrocha/vim-chrome-devtools#4]
1. When trying to uninstall after `nvim +PlugClean` neovim crashes and never finishes clean.
<img width="768" alt="Screen Shot 2020-07-31 at 10 31 02 AM" src="https://user-images.githubusercontent.com/43152353/89045102-f0273a80-d318-11ea-97a6-f45afbaa4673.png">

2. The commands do not load by following the default directions.

**Comment by carlosrocha** [comment]
This could be because of the symlink that is now removed, let me know if you still get it after the update.
